### ISSUE TITLE
Move to yaml secrets everywhere

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpituous#612]
`podman kube play` can [create podman secrests from k8s yaml secrets](https://www.redhat.com/sysadmin/podman-kubernetes-secrets) now. With that, both our OpenShift and systemd deployments can use the same input.

While at it, split the input secrets further: move tasks/s3-keys/ to the top level, and move the github-token to a separate secret out of webhook.

**Comment by martinpitt** [comment]
#617 does the first part of flattening the s3-keys

**Comment by martinpitt** [comment]
Unfortunately podman secrets don't understand k8s style secrets at all. If I have a /tmp/s.yaml with
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: foo-tokens
stringData:
  github-token: "foo bar 123"
  supi: |
    first line
    second line
```

Then `podman play kube  /tmp/s.yaml` works, but it doesn't get mounted as a directory (with the keys as files) as in k8s, but as a single flat yaml file:

```
$ podman run -it --rm --secret=foo-tokens,target=/run/secrets/foo  quay.io/cockpit/tasks cat /run/secrets/foo
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: foo-tokens
stringData:
  github-token: foo bar 123
  supi: |
    first line
    second line
```

In order for this to work, you have to pick out every single key individually with `env.valueFrom.secretKeyRef.{name,key}`, which is awkward.

See https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html

**Comment by martinpitt** [comment]
It actually does work fine when using `podman play kube` for creating the pod as well:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: foo-tokens
stringData:
  github-token: "foo bar 123"
  supi: |
    first line
    second line

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: test1
      image: quay.io/libpod/alpine_nginx:latest
      volumeMounts:
        - name: foo
          mountPath: /etc/foo
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: foo-tokens
        optional: false
```

```
❱❱❱ podman exec -it mypod-test1 ls -l /etc/foo
total 8
-rw-r--r--    1 root     root            11 Apr  8 15:27 github-token
-rw-r--r--    1 root     root            23 Apr  8 15:27 supi
```

So we could go all-in on YAML and use that everywhere. quadlets even support `.kube` files.
